name=MenuCreator
version=1.0.0
author=Jayasankar JP
maintainer=Jayasankar JP <scicopath01@gmail.com>
sentence=Use to create menu very esay way and esay to navigation
paragraph=Provides a clean and simple way to create menu .
category=Utils
url=https://github.com/jayasankar-jp/Menu-Creator
architectures=*
includes=MenuCreator.h
